GeoDjango/geo/urls.py
from django.urls import path
from . import views

app_name = 'geo'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index')
]

GeoDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('',include('GeoDjango.geo.urls')),
    path('admin/', admin.site.urls),
]

GeoDjango/geo/models.py
from django.db import models

# Create your models here.

GeoDjango/geo/views.py
from django.shortcuts import render
from django.views.generic import View
from .utils import yelp_search, get_client_data

class IndexView(View):
	def get(self, request, *args, **kwargs):
		items = []
		city = None
		while not city:
			ret = get_client_data()
			if ret:
				city = ret['city']

		query_term = request.GET.get('key',None)
		local = request.GET.get('location',None)
		location = city
		context = {
			'city':city,
			'busca': False
		}

		if local:
			location = local
		if query_term:
			items = yelp_search(keyword=query_term, location=location)
			context = {
				'items':items,
				'city':location,
				'busca':True
			}
		return render(request,'index.html', context)

GeoDjango/geo/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<!-- CSS only -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale = 1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" />

	<style type="text/css">
	#gmap{
		height: 400px;
		width: 100%;
	}
	</style>
</head>
<body>

	<div class="container">
		{%block main%}
		{%endblock main%}
	</div>
	<!-- JavaScript and dependencies -->
	
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"></script>
	<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
</body>
</html>

GeoDjango/geo/templates/index.html
{%extends 'base.html'%}

{%block main%}
<div class="row">
	<div class="col-sm-6">
		<form action="{%url 'geo:index'%}">
			<div class="form-group">
				<h1><a href="{%url 'geo:index'%}">Buscador</a></h1>
				<h4>[{{city}}] {% if country %}[{{country}}]{% endif %}</h4>
			</div>
			<div class="form-group">
				<input type="text" name="key" class="form-control" placeholder="Type your search">
				<small id="keyHelp" class="form-text text-muted">Like: Mexican Food, Brazilian Food, Asian Food</small>
			</div>
			<div class="form-group">
				<input type="text" name="location" class="form-control" placeholder="Type your location">
				<small id="keyHelp" class="form-text text-muted"></small>
			</div>
			<button type="submit" class="btn btn-primray">Search</button>
		</form>
		{% if 'error' in items %}
			<h3>Nothing was found</h3>
		{% elif busca and items.businesses|length < 1 %}
			<h3>No results for your search</h3>
		{% elif city and items%}
			<h2>Results of your search</h2>
			{% for obj in items.businesses  %}
				<span class="text-info">{{obj.name}} {{city}}</span>
			{% endfor %}
		{% endif %}
	</div>							
</div>
{% if city and items|length > 1 %}
	{% include "maps.html" %}
{% endif %}
{%endblock main%}

GeoDjango/geo/templates/maps.html
<div class="col-sm-6">
	<h3 class="text-primary">Localidades</h3>
	<div id="mapDiv" class="gmap"></div>
</div>
<script type="text/javascript">
	var lat = {{items.businesses.0.coordinates.latitude | safe}};
	var lon = {{items.businesses.0.coordinates.longitude | safe}};

	var map = L.map('mapDiv').setView([lat, lon], 13);
	L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{
		attribution:'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
		maxZoom:18,

	}).addTo(map);

	{% for obj in items.businesses  %}
		var marker = L.marker([{{obj.coordinates.latitude | safe}}, {{obj.coordinates.longitude | safe}}]).addTo(map);
		marker.bindPopup("<b>{{obj.name}}</b><br/>{{obj.location.display_address.0}} {{obj.location.display_address.1}}<br/>{{city}}").openPopup();
	{% endfor %}
</script>